//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::attachments::Entity as Attachments;
pub use super::lists::Entity as Lists;
pub use super::projects::Entity as Projects;
pub use super::settings::Entity as Settings;
pub use super::task_notes::Entity as TaskNotes;
pub use super::tasks::Entity as Tasks;
