//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub list_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub done: i32,
    pub sort_order: f64,
    pub created_at: i64,
    pub updated_at: i64,
    pub deleted_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attachments::Entity")]
    Attachments,
    #[sea_orm(
        belongs_to = "super::lists::Entity",
        from = "Column::ListId",
        to = "super::lists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Lists,
    #[sea_orm(has_many = "super::task_notes::Entity")]
    TaskNotes,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lists.def()
    }
}

impl Related<super::task_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskNotes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
